lib/ui/views/security_view.dart
test/ui/views/security_view_test.dart

Fixed by swapping the TextButton to a Card widget.
dark theme:
<image src="https://user-images.githubusercontent.com/25663435/111914046-d91f8f00-8a46-11eb-8ac7-54302aa9886f.png" width="200"/>
light theme:
<image src="https://user-images.githubusercontent.com/25663435/111914055-e5a3e780-8a46-11eb-8f76-438457203333.png" width="200"/>
closes #56

Remove blue color for emergency procedures

---

lib/core/viewmodels/schedule_viewmodel.dart
lib/l10n/intl_fr.arb
lib/ui/views/schedule_view.dart
test/mock/managers/settings_manager_mock.dart
test/ui/views/schedule_view_test.dart

Will close #89.
The calendar now follows the french date format when in french!

Fix calendar locale and typo.

---

lib/ui/widgets/web_link_card.dart

J'ai testé sur plusieurs téléphones de size différente :

Web link cards

---

README.fr.md
README.md

There was an error while installing the repo on @xeniya-nalivaiko computer. I redid on my computer the steps in `README.md` and this was in fact an error (On windows at least).
Basically, the script `env_variables.sh` when executed, exported 2 variables, but the scope of those variables were only inside the file itself. So when the scripts finished the variables weren't exported in the sh session and they were empty when red from `./scripts/decrypt.sh`
So an easy workaround was to call directly `./scripts/decrypt.sh` from the `env_variables.sh` so it is easier for newcomers to install. I modified the procedure in readme, added the new line in the google drive env_var file and did a PR to discuss the changes, I don't know if there is a better way to handle this. Let me know!

Modified procedure to extract env variables and decrypt files

---

l10n/intl_en.arb
l10n/intl_fr.arb
lib/core/viewmodels/schedule_viewmodel.dart
lib/ui/views/schedule_view.dart
pubspec.lock
pubspec.yaml
test/viewmodels/schedule_viewmodel_test.dart

Closes #393 
Add a toast as suggested in #393 when the user presses the "back to today" button in the schedule view and the currently selected date is already today (which is the default state of the view).
Previously no feedback would be given at all in that case, resulting in a lack of understanding of the purpose of this button.
What it looks like (French version):

Add feedback on today button press when today already selected

---

lib/core/constants/app_info.dart
lib/core/constants/more_ids.dart
lib/core/constants/widget_helper.dart
lib/core/services/in_app_review_service.dart
lib/core/viewmodels/more_viewmodel.dart
pubspec.lock
pubspec.yaml
test/mock/services/home_widget_mock.dart
test/ui/views/more_view_test.dart

Potential solution for #469 
Instead of opening the in-app dialog for reviews, it redirects to the phone's app store.
This is due to an issue with the "in_app_review" flutter package where you can't show the in-app dialog too often, see [here](https://pub.dev/packages/in_app_review#requestreview)

Fix the "Rate us" button not doing anything

---

pubspec.lock
pubspec.yaml

This PR is a small fix for the issue that appeared recently due to some incompatibilities introduced by dependabot updates.
The current state of the main branch is affected by this error, causing the app to remain stuck in the launching state.
Thanks @AntoineLemelin for finding the fix! 🔥 
<details>
<summary>Details of the error</summary>
```
E/flutter (21288): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (21288): #0      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:205:7)
E/flutter (21288): <asynchronous suspension>
E/flutter (21288): #1      MethodChannelFirebase._initializeCore …
```

Fix firebase analytics runtime error

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Comme nous avons maintenant beaucoup de petits changements et beaucoup d'information à donner lors des première PR, j'ai pensé standardiser le template de PR pour aider le mieux possible les membres dans leur création de PR. Dedans, il y a une checklist que chaque contributeur pourra utiliser pour s'assurer que tout est en ordre avant de soumettre leur feature ou bugfix.
Vous pouvez me donner votre avis s'il manque des trucs! 😄

Création d'un template pour les pull_request

---

lib/core/viewmodels/schedule_viewmodel.dart
pubspec.yaml

There was an issue with the Today button in the schedule, causing tests to not pass on every 2nd day of the month.
Changed the way dates are being compared to avoid the test from doing wrong assumptions.
The tests that were not passing before are passing now.
N/A

Fix Today button in schedule

---

.gitattributes
pubspec.yaml

Closes #679 
This small workaround should prevent Github Desktop (on Windows at least) from reformatting all files in the project with new EOL characters and adding them to commits.
Tested on Github Desktop on Windows. Testing that this workaround does not break anything on macOS/Linux environments before merge is not done yet and would be greatly appreciated :)
**[EDIT] MacOS testing successful** (behavior remains unchanged after using the config suggested in this PR)
Not useful here

Add gitattributes to prevent githooks from reformatting all files on commit

---

README.fr.md
README.md

No related issue
With the #707 merge, the build status badge doesn't work.
Both changed URL work.

Fix build status badge in readme

---

.github/workflows/dev-workflow.yaml
pubspec.yaml

During some builds, an error appears with the message
> error: failed to push some refs to 'https://github.com/ApplETS/Notre-Dame'
> hint: Updates were rejected because the tip of your current branch is behind
> hint: its remote counterpart. Integrate the remote changes (e.g.
> hint: 'git pull ...') before pushing again.
> hint: See the 'Note about fast-forwards' in 'git push --help' for details.
[Example](https://github.com/ApplETS/Notre-Dame/actions/runs/3981900332/jobs/6825936065#step:9:76)
I suspect the problem is a racing condition with the bump_version and testing steps in the dev-workflow. With these changes, the testing step will execute after the bump_version step. This will prevent the racing condition.
The build from this PR is the test. The testing step executed after the …

Remove testing racing condition in dev-workflow

---

README.md

No related issue (minor README fix)
Fixed the Play Store badge on the README.
I used [this tool](https://play.cuzi.workers.dev/) to generate the badge since the [old tool](https://github.com/cvzi/playshields) is no longer maintained.
The badge appears correctly on WYSIWYG markdown editors (VS Code preview, Github preview), and the image URL can be opened in a web browser.
VS Code preview:

Fix play store badge

---

.github/workflows/master-workflow.yaml
pubspec.lock
pubspec.yaml

[Bump CumulusDS/get-yaml-paths-action from 1.0.1 to 1.0.2](https://github.com/ApplETS/Notre-Dame/commit/bd77460fe8554186dd85f0653c0952f3eda4e933)
[Bump pub_semver from 2.1.1 to 2.1.4](https://github.com/ApplETS/Notre-Dame/commit/03b7537fd20e3dcaa15ca0ac63d54098e329ae34)
[Bump google_maps_flutter from 2.2.1 to 2.3.0](https://github.com/ApplETS/Notre-Dame/commit/0f724de82b9c143c21134efdfdc21d6c8a42963c)
[Bump connectivity_plus from 2.3.9 to 4.0.2](https://github.com/ApplETS/Notre-Dame/commit/ba6de22d149694fc58d327393939fb7c1140974f)
I launched the application on each bump and navigated through the app too see if something was broken.

Bump pubspec versions

---

lib/core/constants/programs_credits.dart
lib/core/viewmodels/profile_viewmodel.dart

Fixes: #845
I added the new program code in the program credits enum. (Source of the data is my account, I'm in the program)
I added a check to the profile page to set the current program based on the number of credits currently in progress in that program.
As far as my understand of the app goes, the modified part of the view model is self contained and doesn't interact with other parts of the app. The existing unit tests for the widget have been check and all have passed. 
- [✔] I have performed a self-review of my code.
- [N/A] If it is a core feature, I have added thorough tests.
- [N/A] If needed, I added analytics.
- [✔️] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
Personal information removed for privacy reasons. …

Fix program selection for profile page

---

lib/core/viewmodels/dashboard_viewmodel.dart
lib/ui/views/dashboard_view.dart
pubspec.yaml

On Android, the broadcast card, when type = link, launched a native webview with limited controls. The webview has been changed to the already integrated one in the app.

Change broadcast card launch url logic to webview

---

android/app/src/main/res/mipmap-anydpi-v26/launcher_icon.xml
pubspec.yaml

Closes #916
I really just added a single line of XML code, reusing the existing adaptive icon drawable
Tested both in the emulator and on my own phone. Due to not having access to some required keys, and being unable to downgrade dart to the old version that you're using, I had to strip out all flutter code and build it as a normal android app, just for testing. The nature of the change probably doesn't warrant any additional testing.
First screenshot shows the app launcher without Themed Icons enabled, and the second shows how it now looks with Themed Icons enabled.
The ÉTS icon's outline looks less sharp than other icons, I'm not sure what causes that. Since the source file is a PNG, I can't really edit it as I would've done with an SVG. That'll be ok I guess anyway, but if somebody has …

Add android themed icons support

---

lib/ui/views/news_details_view.dart
pubspec.yaml

Added colors for the light them

Light theme news details

---

lib/core/managers/course_repository.dart
lib/core/managers/user_repository.dart
pubspec.yaml

Closes #944 
When launching the app right after it's installed, some cache keys don't exist.
When calling:
- `await _userRepository.getInfo(fromCacheOnly: true)`
- `await _userRepository.getPrograms(fromCacheOnly: true)`
we're getting the info and the programs exclusively from cache, even though they don't exist.
- Running the unit tests
- Uninstalling the app, launching it with the new changes and observing that the profile page loads as expected. 
- *Not sure if this is `patch` or `minor`*

Fixed missing cache keys when loading profile page on first install

---

ios/Podfile.lock
lib/core/managers/course_repository.dart
lib/core/viewmodels/dashboard_viewmodel.dart
lib/ui/views/grade_details_view.dart
lib/ui/widgets/grade_button.dart
pubspec.yaml
test/managers/course_repository_test.dart
test/ui/views/grades_details_view_test.dart

#941 
Instead of just getting the first course review, each course now has a list of course reviews. 
During the evaluation period, the student's grade will be `N/A` until **ALL** the course reviews have been completed.
Previously we only stored one, and because of this it would cause issues if there were more than 1 course review required for a single course.
*Note that the changes in this PR are dependant on https://github.com/ApplETS/ETS-API-Clients/pull/36.*
This has been tested by running the unit tests.

Changes to accomodate multiple course reviews for a single course

---

lib/features/student/grades/widgets/grade_evaluation_tile.dart
pubspec.lock
pubspec.yaml

When expanding a grade evaluation tile, the text disappears and an `RenderBox was not laid out` exception.
The solution is to use `SingleChildScrollView` instead of `Marquee`.
The current behaviour is that if an evaluation title is too long, it automatically flows on the screen horizontally.
Advantages:
- Reduces code complexity
- Most of the current behavior is retained
- Compatible with other font sizes
Disadvantages:
- The text does not flow when a width overflow is present.
- Users will have to scroll manually when a text overflow is present.
- On my phone

Change marquee to singlescrollview

---

lib/features/app/navigation/router.dart

closes #722, #141
Pour les pages ou le geste devrait être possible, utilisation de MaterialPageRoute.
On perds l'animation où la page des notes arrive à l'écran depuis le bas.
Sur iOS et Android

Permettre aux utilisateurs sur iOS de swipe pour retourner à la page précédente

---

lib/features/app/widgets/base_scaffold.dart
lib/main.dart
pubspec.yaml

Closes #1064 
Faire en sorte que la handle au base de l'écran ait un background transparent
En paysage, ne pas afficher la barre de statut.
Tested on android, light and dark mode, landscape and portrait.

Implement edge to edge on android

---

ios/Podfile.lock
lib/features/schedule/schedule_default/schedule_default_viewmodel.dart
pubspec.yaml

Closes #1127 
The issue is because `.weekday` returns the weekday index with Monday (1) being the first day and Sunday (7) being the last.
When we try to calculate `daysToAdd` on a Sunday, we're doing `eventData.dayOfTheWeek - 7`.
For example if we have an event on Monday, the calculation will be `daysToAdd = 1 - 7`.
Because of this, the `targetDate` becomes `-6` (6 days in the past).
Since the date is in the past, it doesn't get show on the calendar because the default calendar only displays the current week.
I decided to create a method to return `0` as the index for Sunday instead of `7`.
I'm open to other solutions, I feel like this is the simplest solution at the moment.
- Manual testing (changed the device's current date to all days of the week)
- Ran the unit tests

Fixed empty schedule on sundays

---

ios/Podfile.lock
lib/data/services/signets-api/models/course.dart
test/ui/student/grades/grade_details/widgets/grades_details_view_test.dart

#1161 
The `allReviewsCompleted` flag in `course.dart` now checks if all the **active** course reviews have been completed.
An *active* course review represents a course review which the `startAt` date is before the current date and the `endAt` date is after the current date.
Manual testing and existing/new unit tests

Check if the active course reviews are completed instead of all course reviews

---

lib/data/services/signets-api/models/course_summary.dart
lib/ui/student/grades/grade_details/widgets/grade_details_view.dart
lib/ui/student/grades/widgets/grade_button.dart
lib/ui/student/grades/widgets/grade_evaluation_tile.dart
lib/utils/utils.dart
pubspec.yaml
test/ui/student/grades/grade_details/widgets/grades_details_view_test.dart
test/ui/student/grades/widgets/grade_button_test.dart
test/ui/student/grades/widgets/grade_evaluation_tile_test.dart

#885 
Grades are init at at `N/A` when they are `null` instead of `0%`. This is to avoid confusing the user in the rare cases where the teacher doesn't post all the students grades at the same time.
Manual testing and unit tests

Init grades at N/A instead of 0%

---

ios/Podfile.lock
lib/ui/student/profile/view_model/profile_viewmodel.dart
lib/ui/student/profile/widgets/profile_view.dart
pubspec.yaml
test/ui/student/profile/view_model/profile_viewmodel_test.dart
test/ui/student/profile/widgets/profile_view_test.dart

#1126 
Added a function to determine the current program. 
```
Program getCurrentProgram() {
RegExp regExp = RegExp(r"^Microprogramme de \d+\w* cycle en enseignement coopératif");
List<Program> nonInternshipPrograms =
programList.where((item) => !regExp.hasMatch(item.name) && item.status.toLowerCase() == "actif").toList();
return nonInternshipPrograms.last;
}
```
We look for programs that don't match the regex pattern but that are also `status == "actif"`.
I can't confirm if this covers all the cases for *all* internships in *all* programs.
I would much rather filter out by `.code`.
Ex: `0725 -> Stage I`, `0726 -> Stage II`, etc. However, I also can't confirm if we have all the codes for all internship programs. 
Manual testing and unit tests

Internship programs shouldn't be the default

---

lib/ui/dashboard/widgets/schedule_card.dart
pubspec.yaml

issue #1191 
Deleted the gesture causing the issue reported
Clicking the 'Horaire' text on the main page of the app now works as it should, not doing anything and not showing a blank page.

Issue-1191-correction
