lib/ui/widgets/web_link_card.dart
=> Change image color for quick links

lib/core/managers/settings_manager.dart, lib/main.dart, test/managers/settings_manager_test.dart
Fix locale error after a user logs out and log in without killing the application. Closes #107
=> Fix locale error when log out then log in.

lib/core/services/navigation_service.dart, lib/core/viewmodels/choose_language_viewmodel.dart, lib/core/viewmodels/login_viewmodel.dart, lib/core/viewmodels/not_found_viewmodel.dart, lib/core/viewmodels/startup_viewmodel.dart, lib/ui/widgets/bottom_bar.dart, pubspec.lock, pubspec.yaml, test/ui/widgets/bottom_bar_test.dart, test/viewmodels/choose_language_viewmodel_test.dart, test/viewmodels/login_viewmodel_test.dart, test/viewmodels/not_found_viewmodel_test.dart, test/viewmodels/startup_viewmodel_test.dart
=> updated back button behavior

.github/workflows/main-workflow.yaml, lib/core/managers/course_repository.dart, lib/core/managers/user_repository.dart, pubspec.yaml, test/helpers.dart, test/managers/course_repository_test.dart, test/managers/user_repository_test.dart, test/viewmodels/dashboard_viewmodel_test.dart, test/viewmodels/grades_details_viewmodel_test.dart, test/viewmodels/grades_viewmodel_test.dart, test/viewmodels/more_viewmodel_test.dart, test/viewmodels/profile_viewmodel_test.dart, test/viewmodels/schedule_settings_viewmodel_test.dart, test/viewmodels/schedule_viewmodel_test.dart
It's been some time since I did a PR ahah.
This PR contains 2 fixes:
- the last day of the session was excluded from the active session which prevented the schedule from being updated and prevented the progress bar to reach 100%. 
- fix #97 :)
=> Fix last day of session excluded from current session and balance that doesn't update

analysis_options.yaml, lib/core/constants/preferences_flags.dart, lib/core/constants/update_code.dart, lib/core/managers/settings_manager.dart, lib/core/services/github_api.dart, lib/core/services/navigation_service.dart, lib/core/services/siren_flutter_service.dart, lib/core/viewmodels/dashboard_viewmodel.dart, lib/core/viewmodels/startup_viewmodel.dart, lib/l10n/intl_en.arb, lib/l10n/intl_fr.arb, lib/locator.dart, lib/ui/router.dart, lib/ui/views/dashboard_view.dart, lib/ui/views/startup_view.dart, pubspec.lock, pubspec.yaml, test/helpers.dart, test/mock/services/siren_flutter_service_mock.dart, test/ui/views/dashboard_view_test.dart, test/viewmodels/startup_viewmodel_test.dart
Make the updater alert the user to update your app. The app ask when a new version is available, when a minor or major version has changed. Though, when a revision has changed it will force the user to update.
<details>
<summary>Alert UI visual</summary>
</details>
closes #282
=> Updater new version

lib/core/viewmodels/web_link_card_viewmodel.dart, pubspec.yaml
=> removed false crashlytics message

lib/core/managers/settings_manager.dart, lib/core/services/preferences_service.dart, lib/core/viewmodels/dashboard_viewmodel.dart, lib/core/viewmodels/schedule_settings_viewmodel.dart, lib/core/viewmodels/schedule_viewmodel.dart, pubspec.yaml, test/mock/managers/settings_manager_mock.dart, test/ui/widgets/schedule_settings_test.dart, test/viewmodels/dashboard_viewmodel_test.dart, test/viewmodels/schedule_settings_viewmodel_test.dart, test/viewmodels/schedule_viewmodel_test.dart
https://user-images.githubusercontent.com/37625944/150659842-5a7aef11-32d2-453a-8934-07409f300b78.mp4
Closes #308
=> Course Activity Dashboard

lib/core/viewmodels/grades_details_viewmodel.dart, pubspec.yaml
=> Add verification

lib/core/viewmodels/web_link_card_viewmodel.dart, pubspec.lock, pubspec.yaml
[flutter_customs_tabs](https://pub.dev/packages/flutter_custom_tabs) is much more maintained and seems more up to date than the package we were using before. I even put an animation on the page load with it 😄 
I can't really fully test the new package because of the bug right now. But as soon as I will be able to, I will drop some screenshot here :) At least for now, it doesn't crash on launch should be a good sign!
Edit: There it is! It looks like that really close to the previous behavior :
closes #304 
closes #289
=> Fix Crash on app open and on tab close

lib/core/viewmodels/contributors_viewmodel.dart, pubspec.yaml
Removed dependabot[bot] from the list of contributors.
=> Remove dependabot from contributors

lib/core/viewmodels/startup_viewmodel.dart, pubspec.yaml, test/viewmodels/startup_viewmodel_test.dart
=> Fix infinite loading for android users

lib/core/constants/widget_helper.dart, pubspec.lock, pubspec.yaml, test/mock/services/home_widget_mock.dart
Closes #467 
This should fix the build error that happens with Flutter 3 and home_widget prior to 0.1.6.
=> Fix build for Flutter 3.0.0 and above

.github/workflows/devtools-workflow.yaml, pubspec.yaml
=> [CI] Fix PR size labeler

.github/pull_request_template.md, .github/workflows/main-workflow.yaml, pubspec.yaml, test/ui/views/about_view_test.dart, test/ui/views/choose_language_view_test.dart, test/ui/views/dashboard_view_test.dart, test/ui/views/feedback_view_test.dart, test/ui/views/grades_details_view_test.dart, test/ui/views/grades_view_test.dart, test/ui/views/more_view_test.dart, test/ui/views/not_found_view_test.dart, test/ui/views/profile_view_test.dart, test/ui/views/quick_links_view_test.dart, test/ui/views/schedule_view_test.dart, test/ui/views/settings_view_test.dart, test/ui/views/student_view_test.dart, test/ui/widgets/schedule_settings_test.dart
closes: #693 
- Remove the [CI UPDATE GOLDENS] check from the ci main_workflow.yaml file (always update the golden files).
- Update the golden tests to skip them on platforms other than Linux.
- Add check in pull_request_template file asking to verify if golden files changes were verified and accepted.
=> 693: fix golden testing

.github/workflows/release-workflow.yaml, pubspec.yaml
=> [TEST-CD] Update release-workflow.yaml

.github/workflows/main-workflow.yaml, android/app/build.gradle, pubspec.lock, pubspec.yaml
=> Bump pubspec version

.github/workflows/main-workflow.yaml, pubspec.lock, pubspec.yaml
=> Bump pubspec version 

lib/core/managers/course_repository.dart, lib/core/services/internal_info_service.dart, lib/core/services/remote_config_service.dart, lib/core/viewmodels/dashboard_viewmodel.dart, lib/core/viewmodels/grades_details_viewmodel.dart, lib/core/viewmodels/grades_viewmodel.dart, lib/core/viewmodels/more_viewmodel.dart, lib/core/viewmodels/outage_viewmodel.dart, lib/core/viewmodels/schedule_viewmodel.dart, lib/main.dart, lib/ui/utils/discovery_components.dart, lib/ui/views/feedback_view.dart, lib/ui/views/schedule_view.dart, pubspec.yaml, test/ui/views/not_found_view_test.dart, test/ui/widgets/grade_button_test.dart, test/viewmodels/not_found_viewmodel_test.dart, test/viewmodels/web_link_card_viewmodel_test.dart
Add the possibility to swipe in the calendar to change day or weak depend on your chosen mode.
=> Add the possibility to swipe to go to the next day or weak

lib/core/constants/app_info.dart, pubspec.yaml, test/ui/views/login_view_test.dart
Change email 'etsmtl.net' to 'ens.etsmtl.ca'
=> Update club email

lib/core/services/github_api.dart, lib/core/viewmodels/feedback_viewmodel.dart, lib/ui/views/feedback_view.dart, pubspec.yaml, test/viewmodels/feedback_viewmodel_test.dart
CLoses #798
Change the 'email' format and fix the label
N/A
N/A
=> Fix bug/enhancement report

lib/core/constants/router_paths.dart, lib/core/viewmodels/outage_viewmodel.dart, lib/ui/router.dart, pubspec.yaml
close #794 
Change the redirection for the startup page on click of the refresh button.
=> Fix the bug from the outage page

README.fr.md
No related issue
The french README wasn't updated. I updated the doc according to the english version.
I look at the english README and compared it to the french README
no screenshots
=> chore: update french README

.github/workflows/devtools-workflow.yaml, .github/workflows/versionning-workflow.yaml
Put bump_version into its own workflow
=> Put bump_version into its own workflow

lib/ui/utils/app_theme.dart, pubspec.yaml
closes: #955 
Put Colors.white in darkTheme textStyle
On device
=> Fix dark theme text color

lib/features/student/profile/profile_view.dart, lib/features/student/profile/profile_viewmodel.dart, pubspec.yaml, test/features/student/profile/profile_viewmodel_test.dart
=> Remove the decimal in program completion

l10n/intl_en.arb, l10n/intl_fr.arb, lib/features/app/error/outage/outage_view.dart, lib/features/app/error/outage/outage_viewmodel.dart, lib/features/app/error/outage/widgets/outage_image_section.dart, lib/features/app/error/outage/widgets/outage_social_section.dart, lib/features/app/error/outage/widgets/outage_text_section.dart, lib/features/ets/quick-link/quick_links_view.dart, lib/features/ets/quick-link/widgets/security-info/emergency_view.dart, lib/features/ets/quick-link/widgets/security-info/models/emergency_procedures.dart, test/features/ets/quick-link/widgets/security-info/emergency_view_test.dart
Created a new remote config, activated and deactivated it.
=> Outage view refactoring

.github/composite/tag-validation/action.yaml
=> Fix tag validation

.github/composite/flutter-setup/action.yaml
=> Update CI flutter versions

.github/composite/flutter-setup/action.yaml, android/app/build.gradle, android/app/src/debug/AndroidManifest.xml, android/app/src/main/AndroidManifest.xml, android/app/src/profile/AndroidManifest.xml, android/build.gradle, ios/Podfile.lock, lib/features/app/error/outage/outage_view.dart, lib/features/app/error/outage/outage_viewmodel.dart, lib/features/app/error/outage/widgets/outage_text_section.dart, lib/features/app/widgets/base_scaffold.dart, lib/features/dashboard/dashboard_view.dart, lib/features/dashboard/widgets/course_activity_tile.dart, lib/features/ets/events/author/author_view.dart, lib/features/ets/events/news/news-details/news_details_view.dart, lib/features/ets/events/report-news/report_news_widget.dart, lib/features/ets/quick-link/widgets/security-info/emergency_view.dart, lib/features/ets/quick-link/widgets/security-info/security_view.dart, lib/features/more/faq/faq_view.dart, lib/features/more/feedback/feedback_view.dart, lib/features/more/more_viewmodel.dart, lib/features/schedule/schedule_viewmodel.dart, lib/features/student/grades/grade_details/grades_details_viewmodel.dart, lib/features/student/grades/grades_viewmodel.dart, lib/features/welcome/login/login_view.dart, pubspec.lock, pubspec.yaml, test/features/dashboard/dashboard_view_test.dart, test/features/dashboard/dashboard_viewmodel_test.dart, test/features/ets/quick-link/widgets/security-info/emergency_view_test.dart
=> Update ci flutter version

pubspec.lock, pubspec.yaml
N/A
Empêcher que calendar view soit update automatiquement, la dernière mise à jour a des problèmes
N/A
=> Empêcher une mise a jour de dépendance de briser le projet

lib/ui/schedule/schedule_default/widgets/schedule_default.dart, lib/ui/schedule/widgets/schedule_view.dart, pubspec.lock, pubspec.yaml
N/A
Update calendar_view
Works on my machine
=> Update calendar view

lib/ui/schedule/view_model/calendars/calendar_viewmodel.dart, lib/ui/schedule/view_model/calendars/week_viewmodel.dart, lib/utils/utils.dart, pubspec.yaml, test/ui/schedule/widgets/calendars/month_view_test.dart, test/ui/schedule/widgets/calendars/week_view_test.dart
Fixed issue caused by date change
=> Fix unit tests

lib/ui/more/faq/widgets/action_card.dart, lib/ui/more/faq/widgets/faq_view.dart, lib/ui/more/faq/widgets/question_card.dart, pubspec.yaml
Closes: #1134
Refactors faq_view with new `QuestionCard` and `ActionCard` widgets to improve reusability.
- Ensured that the FAQ view looks the same as before.
- Ensured that `QuestionCard` and `ActionCard` behave the same as before.
N/A
=> Refactor faq_view

.github/workflows/release-workflow.yaml, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, ios/Runner/Info.plist
Changelogs space is too little to put details. So there's no need to add it in the CI. And since we use echo, there are a lot of characters that we need to escape.
=> Remove changelog

lib/ui/student/session_schedule/widgets/session_schedule.dart, pubspec.yaml
=> Fix appbar color in session schedule

ios/Podfile.lock, lib/ui/schedule/view_model/calendars/week_viewmodel.dart, lib/ui/schedule/widgets/calendars/week_calendar.dart, pubspec.yaml
N/A
Lorsque l'on passe d'une page à l'autre, le mouvent de la page ne suivait pas le mouvement du doigt.
Ça marche
=> Correctif swipe vue semaine

lib/ui/core/ui/navigation_menu/navigation_menu.dart, lib/ui/core/ui/root_view.dart
N/A
Fixed small safe area related issues
Manual tests on android and ios
Same look except it won't clip outside the screen
=> Fix safe area of navigation menu

l10n/intl_en.arb, l10n/intl_fr.arb, lib/data/models/quick_links.dart, pubspec.yaml
closes #847 
adds three new quicklinks (for the internship portal, eportfolio and egrants websites respectively)
Each link opens correctly when clicked.
Note - The internship portal looks really ugly (borderline unreadable) on mobile... It might be worth omitting.
=> internship portal, eportfolio and egrants quicklinks

lib/ui/dashboard/widgets/dashboard_view.dart, lib/ui/startup/widgets/startup_view.dart, pubspec.yaml
On some older versions of Android the translucent look of the gesture bar might not have been applied correctly
=> Translucent gesture bar

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, ios/Runner/Info.plist, ios/Runner/Runner.entitlements, ios/fastlane/Matchfile, pubspec.yaml
=> Fix ios build
